spring:
  datasource:
    url: jdbc:mariadb://${DB_DESENV_SERVER:localhost}:${DB_DESENV_PORT:3306}/${DB_DESENV_NAME:desenv-spring-pj-motos}?createDatabaseIfNotExist=true
    username: ${DB_DESENV_USERNAME:root}
    password: ${DB_DESENV_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
