spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/2tdspf-authentication?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create